repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.8'
    hooks:
      - id: ruff
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
      - id: pip-compile
        name: pip-compile requirements.txt
        args: [--strip-extras, --output-file=requirements.txt]
        files: ^(pyproject\.toml|requirements\.txt)$
      - id: pip-compile
        name: pip-compile requirements-test.txt
        args: [--extra=test, --strip-extras, --output-file=requirements-test.txt]
        files: ^(pyproject\.toml|requirements-test\.txt)$
      - id: pip-compile
        name: pip-compile requirements-dev.txt
        args: [--extra=dev, --strip-extras, --output-file=requirements-dev.txt]
        files: ^(pyproject\.toml|requirements-dev\.txt)$
